### ISSUE TITLE
加入传入参数的功能

### ISSUE THREAD

**Issue by Leave-Time** [MeetWq/nonebot-plugin-alias#1]
可否加入传入参数的功能，比如：
原bot有一个指令 `/command`后面能传入参数`-arg`
那重命名为`command` 后，可否也能让它后面传入参数？
比如加入`{arg}`，将重命名规则变为：
`/command -{arg}` =` command {arg}`
然后使用时，`command arg` 就能定向到` /command -arg`
类似的功能能添加吗，谢谢。

**Comment by MeetWq** [comment]
使用 `alias command="/command"` 之后，是可以用 `command -arg` 的；
如果一定要用 `command arg` ，一个比较笨的方法是为每个参数都创建一个 `alias "command arg"="/command -arg"`

传入参数的话，我目前的想法是加入类似shell的参数，如：`alias command="/command -$1"`，但还没想好该怎么实现
